### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Bomban1** [ShatReal/drag-drop-inventory#1]
When I drag and drop an item onto the same slot it was at before the game crashes

**Comment by ShatReal** [comment]
Oh shoot, I'll try to fix this as soon as possible!

**Comment by Bomban1** [comment]
Thanks, I think I just found a work around but there are some errors that show up but dont affect anything in the game. 

In the slot script I tweaked the _drop_data function:

func _drop_data(_at_position: Vector2, data: Variant) -> void:
	if get_child_count() > 0:
		var item := get_child(0)
		if data.get_parent():
			data.get_parent().add_child(item)
			remove_child(item)
	if data.get_parent():
		data.get_parent().remove_child(data)
	add_child(data)
	
	
	It's pretty choppy but it worked for me.

**Comment by ShatReal** [comment]
I couldn't replicate the error, but good that you found something

**Comment by Bomban1** [comment]
It might be something on my end then. I have a camera2D zoomed in pretty close because my game is 16x and I didn't want to scale anything up. The camera also caused a separate issue but that was just because of the way the default drag and drop features are made so there isn't much to do about that and it wasn't to hard to fix. Thanks for making this demo it was really helpful!

**Comment by jlucaso1** [comment]
Another solution (check if the move object and the target has the same reference):
```gdscript
func _drop_data(_at_position: Vector2, data: Variant) -> void:
	if get_child_count() > 0:
		var item := get_child(0)
		if item == data: return # <-- add this line
		remove_child(item)
		data.get_parent().add_child(item)
	data.get_parent().remove_child(data)
	add_child(data)
```

**Comment by Bomban1** [comment]
This worked like a charm! thanks
